
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('100', 'Team Oakley', 'Husani Oakley', 'http://www.youtube.com/watch?v=oHg5SJYRHA0', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('101', 'Team Tighe', 'Jason Tighe', 'http://www.youtube.com/watch?v=cM030uAzLiw', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('102', 'Team Felarca', 'Lee Felarca', 'http://www.youtube.com/watch?v=-SjS9F5aV40', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('103', 'Team Jones', 'Sean Jones', 'http://www.youtube.com/watch?v=vdrqA93sW-8', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('104', 'Team Nan', 'Sunny Nan', 'http://www.youtube.com/watch?v=0Q3iSg8GQrk', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('105', 'Team Kaplan', 'Brandon Kaplan', 'http://www.youtube.com/watch?v=OPYcFQxsKlQ', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('106', 'Team Newman', 'Hana Newman', 'http://www.youtube.com/watch?v=6dlyCTswYH0', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('107', 'Team Pyle', 'Christena Pyle', 'http://www.youtube.com/watch?v=lym6rUzivnU', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('108', 'Team Shaw', 'Daniel Shaw', 'http://www.youtube.com/watch?v=IhPNek8XAdk', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('109', 'Team Estevez', 'Victoria Estevez', 'http://www.youtube.com/watch?v=ImTvDDbSZys', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('110', 'Team Maleh', 'Marc Maleh', 'http://www.youtube.com/watch?v=LsXRj89cWa0', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('111', 'Team Ball', 'Marshall Ball', 'http://www.youtube.com/watch?v=TK5lO_CUuFs', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');

INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('112', 'Team Obama', 'Barack Obama', 'http://www.youtube.com/watch?v=3KNpn-XGM04&', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('113', 'Team Bush', 'Dubya', 'http://www.youtube.com/watch?v=vbB-23aF14s', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('114', 'Team Clinton', 'Bill Clinton', 'http://www.youtube.com/watch?v=u33ivAO_Zyk', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('115', 'Team Bush Senior', 'George H. W. Bush', 'http://www.youtube.com/watch?v=1HZWPsGHHVc', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('116', 'Team Reagan', 'Ronald Reagan', 'http://www.youtube.com/watch?v=LMcjzGMlwOo', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('117', 'Team Carter', 'Jimmy Carter', 'http://www.youtube.com/watch?v=nmP9Shki6_I', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('118', 'Team Ford', 'Gerald Ford', 'http://www.youtube.com/watch?v=moWKD0wuCFM', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('119', 'Not Public Yet', 'Not Public Yet', 'http://www.youtube.com/watch?v=YQRKlQox-OQ', '0', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('120', 'Team LBJ', 'Lyndon B. Johnson', 'http://www.youtube.com/watch?v=F92k3fGKtFU', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('121', 'Team JFK', 'John F. Kennedy', 'http://www.youtube.com/watch?v=rQOBxL7S0OQ', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');

INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('122', 'Team Kirk', 'James Kirk', 'http://www.youtube.com/watch?v=_PKUy5JB3cw', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('123', 'Team Picard', 'Jean-Luc Picard', 'http://www.youtube.com/watch?v=X8oQKDfciTE', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('124', 'Team Sisko', 'Benjamin Sisko', 'http://www.youtube.com/watch?v=VIjablDh1MM', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('125', 'Team Janeway', 'Kathryn Janeway', 'http://www.youtube.com/watch?v=bdz8iQgifVw', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('126', 'Team Spock', 'Spock', 'http://www.youtube.com/watch?v=qcVc87YerUo', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('127', 'Team McCoy', 'Leonard McCoy', 'http://www.youtube.com/watch?v=750J0YShki4', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('128', 'Team Scotty', 'Montgomery Scott', 'http://www.youtube.com/watch?v=RZSGJdJ-8ns', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('129', 'Team Uhura', 'Nyota Uhura', 'http://www.youtube.com/watch?v=SbEh23FdkUs', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');



INSERT INTO leagueinviter (league_id, league_name, league_manager_name, youtube_url, status, youtube_bucket, date_video_created, s3_url) VALUES ('', '', '', '', 'CREATED', '1', NOW(), 'http://stage.fqc.encoded.s3.amazonaws.com/_7880.mp4');
